[package]
name = "gb_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.7.2"
macroquad = "=0.4.5"
log = "0.4.21"
simple_logger = "5.0.0"

[features]
ci = []
