name: Website Upload
on:
  push:
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/**'
    # We only run this GitHub action upon new commits to `main`
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install

      - name: Build
        run: bun run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/dist
          # Remove previous build files
          clean: true
          # Do not remove the `.nojekyll` file: we have manually added an empty `.nojekyll` file at the root of the `gh-pages` branch and we don't want having to re-create it after each build.
          clean-exclude: |
            .nojekyll
            CNAME
